### ISSUE TITLE
Suggestion: SIAD properly

### ISSUE THREAD

**Issue by Chamelllemon** [Friends-of-Monika/mas-selfharm#1]
### What is your suggestion about?

Monika can randomly say that today's SIAD even though today isn't March 1st, maybe make connect this topic to a date? Like she can bring it up but she won't say that it's today if today isn't March 1st, obviously

I didn't notice that it was a final update...I'll just leave this here

**Comment by dreamscached** [comment]
The update isn't final, I still maintain the mod. I'll look into it and release a bugfix as soon as I'm able to.

P.S. The latest release was labelled as 'the final **content** update' because Otter, person who's the original idea author and content maker for this mod, is no longer around in MAS community, and I merely keep this mod up to date with MAS and fix issues.

**Comment by dreamscached** [comment]
Resolved in #2 (6f6e94b1), will be rolled out in 1.0.8
